CREATE TABLE IF NOT EXISTS LOGS
(
  TS TIMESTAMP PRIMARY KEY NOT NULL,
  PROTOCOL VARCHAR(15) NOT NULL,
  SYSTEMNAME VARCHAR(50) NOT NULL,
  INTEGRATIONPOINTNAME VARCHAR(50) NOT NULL,
  FULLENDPOINT VARCHAR(250) NOT NULL,
  SHORTENDPOINT VARCHAR(50) NOT NULL,
  MESSAGESTATE VARCHAR(20) NOT NULL,
  MESSAGEPREVIEW VARCHAR(50) NOT NULL,
  MESSAGE CLOB NOT NULL
);
CREATE INDEX IF NOT EXISTS LOGS_MESS_PREVIEW_INDEX ON LOGS (MESSAGEPREVIEW);
CREATE INDEX IF NOT EXISTS LOGS_TS_INDEX ON LOGS (TS);
